apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - cinder-backend-patch.yaml
  - glance-backend-patch.yaml

configMapGenerator:
  - name: storage-config
    literals:
      - backend=ceph
      - pool=openstack
