---
apiVersion: v1
kind: Secret
metadata:
  name: staging-extra-secret
  namespace: openstack
type: Opaque
stringData:
  environment: staging
  extra-config: |
    # Environment-specific configuration
    debug: false
