---
apiVersion: v1
kind: Secret
metadata:
  name: dataplane-ansible-ssh-private-key-secret
  namespace: openstack
type: Opaque
data:
  ssh-privatekey: ""  # Will be populated
  ssh-publickey: ""   # Will be populated
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-migration-ssh-key
  namespace: openstack
type: Opaque
data:
  ssh-privatekey: ""  # Will be populated
  ssh-publickey: ""   # Will be populated
