apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - osp-secret.yaml
  - dataplane-secrets.yaml

secretGenerator:
  - name: additional-passwords
    literals:
      - additional-service-password=changeme
    options:
      disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/component: secrets
  app.kubernetes.io/part-of: rhoso
