apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: deployment-scripts
    files:
      - scripts/post-deployment.sh
      - scripts/validation.sh

commonLabels:
  app.kubernetes.io/component: configmaps
  app.kubernetes.io/part-of: rhoso
