apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - prometheus-rules.yaml
  - grafana-dashboards.yaml

configMapGenerator:
  - name: monitoring-config
    files:
      - dashboards/nova-dashboard.json
      - dashboards/neutron-dashboard.json
