apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openstackcontrolplane.yaml
  - services-config.yaml

configMapGenerator:
  - name: service-config-overrides
    files:
      - configs/nova.conf
      - configs/neutron.conf
      - configs/cinder.conf

commonLabels:
  app.kubernetes.io/component: controlplane
  app.kubernetes.io/part-of: rhoso
