apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openstack

resources:
  # Networking resources
  - networking/

  # Control plane resources
  - controlplane/

  # Data plane resources
  - dataplane/

  # Secrets
  - secrets/

  # ConfigMaps
  - configmaps/

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: rhoso
  app.kubernetes.io/instance: rhoso-deployment
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  rhoso.openstack.org/version: "18.0"
